<?php

namespace App\Services;

use App\Models\Company;
use App\Models\Vehicle;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class VehicleService
{
    public function paginate(array $filters, int $perPage = 20): LengthAwarePaginator
    {
        $query = Vehicle::query()->with('assignedDriver');

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (! empty($filters['search'])) {
            $search = $filters['search'];
            $query->where(function ($q) use ($search) {
                $q->where('registration_number', 'like', "%{$search}%")
                    ->orWhere('make', 'like', "%{$search}%")
                    ->orWhere('model', 'like', "%{$search}%");
            });
        }

        return $query->orderByDesc('id')->paginate($perPage);
    }

    public function create(Company $company, array $data): Vehicle
    {
        $this->assertWithinPlanLimit($company);

        return DB::transaction(function () use ($data) {
            // company_id is auto-filled by BelongsToCompany on creating(),
            // qr_code_value is auto-generated by Vehicle::booted() — neither
            // is ever accepted from client input, by design.
            $vehicle = Vehicle::create($data);

            if (! empty($data['assigned_driver_id'])) {
                $this->syncDriverAssignment($vehicle, $data['assigned_driver_id']);
            }

            return $vehicle->fresh('assignedDriver');
        });
    }

    public function update(Vehicle $vehicle, array $data): Vehicle
    {
        return DB::transaction(function () use ($vehicle, $data) {
            $vehicle->update($data);

            if (array_key_exists('assigned_driver_id', $data)) {
                $this->syncDriverAssignment($vehicle, $data['assigned_driver_id']);
            }

            return $vehicle->fresh('assignedDriver');
        });
    }

    public function delete(Vehicle $vehicle): void
    {
        $vehicle->delete(); // soft delete — history (journeys, fuel, maintenance) stays intact
    }

    /**
     * A vehicle can only be "assigned" to one driver at a time — keep that
     * consistent from the vehicle side without requiring two API calls.
     */
    protected function syncDriverAssignment(Vehicle $vehicle, ?int $driverId): void
    {
        $vehicle->assigned_driver_id = $driverId;
        $vehicle->save();
    }

    protected function assertWithinPlanLimit(Company $company): void
    {
        $subscription = $company->activeSubscription;

        if (! $subscription) {
            throw ValidationException::withMessages([
                'company' => ['No active subscription found for this company.'],
            ]);
        }

        $currentCount = Vehicle::withoutTrashed()->count(); // already company-scoped

        if ($currentCount >= $subscription->plan->max_vehicles) {
            throw ValidationException::withMessages([
                'plan_limit' => ["Your plan allows a maximum of {$subscription->plan->max_vehicles} vehicles. Upgrade to add more."],
            ]);
        }
    }
}